---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[swarm::default]
    attributes:

  - name: service
    run_list:
      - recipe[swarm::service]
    attributes:
