---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[swarm::service]
      - recipe[swarm::default]
    attributes:

  - name: service
    run_list:
      - recipe[swarm::service]
    attributes:

  - name: manager
    run_list:
      - recipe[swarm::service]
      - recipe[swarm::manager]
    attributes:
      swarm:
        discovery:
          token: fba21ffa43f1e13ef799d293eb74979a

  - name: worker
    run_list:
      - recipe[swarm::service]
      - recipe[swarm::worker]
    attributes:
      swarm:
        discovery:
          token: fba21ffa43f1e13ef799d293eb74979a
